---
Name: suilven-blog-extras
---

SilverStripe\Blog\Model\BlogPost:
  extensions:
  - Suilven\Blog\FeaturedBlogPost
  - Suilven\Blog\FeaturedImageCaption

PageController:
  extensions:
    - Suilven\Blog\FeaturedBlogPosts
